[package]
name = "gamechooser2-client"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
gamechooser-core = { path = "../../gamechooser-core" }
wasm-bindgen = "0.2.63"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
  'Document',
  'HtmlInputElement',
  'HtmlParagraphElement',
  'HtmlSpanElement',
  'Storage',
  'Window',
]
